#!/bin/sh

echo ""
echo "For administrative and funding reasons, Bioconductor"
echo "keeps track of each time a Bioconductor AMI is launched."
echo "No identifying information is kept. By using this AMI,"
echo "you consent to this tracking."
echo ""